//streamers/youtube-scraper
export interface YoutubeScraperConfig {
  dateFilter: string;
  downloadSubtitles: boolean;
  hasCC: boolean;
  hasLocation: boolean;
  hasSubtitles: boolean;
  is360: boolean;
  is3D: boolean;
  is4K: boolean;
  isBought: boolean;
  isHD: boolean;
  isHDR: boolean;
  isLive: boolean;
  isVR180: boolean;
  lengthFilter: string;
  maxResultStreams: number;
  maxResults: number;
  maxResultsShorts: number;
  preferAutoGeneratedSubtitles: boolean;
  saveSubsToKVS: boolean;
  searchQueries: string[];
  sortingOrder: string;
}

//pintostudio/youtube-transcript-scraper
export interface YoutubeTranscriptConfig {
  videoUrl: string;
}

// jupri/reddit
export interface RedditScraperConfig {
  dev_dataset_clear: boolean;
  dev_no_strip: boolean;
  filters: {
    mode: string; //'posts' | 'comments'
    safe: boolean;
    sort: string; //'RELEVANCE' | 'NEW' | 'TOP' | 'HOT';
    timing: string; //'hour' | 'day' | 'week' | 'month' | 'year' | 'all';
    types: string[]; //('text' | 'image' | 'video' | 'link' | 'poll')[];
  };
  limit: number;
  query: string[];
}
