//streamers/youtube-scraper
export interface YoutubeScraperConfig {
  dateFilter: string;
  downloadSubtitles: boolean;
  hasCC: boolean;
  hasLocation: boolean;
  hasSubtitles: boolean;
  is360: boolean;
  is3D: boolean;
  is4K: boolean;
  isBought: boolean;
  isHD: boolean;
  isHDR: boolean;
  isLive: boolean;
  isVR180: boolean;
  lengthFilter: string;
  maxResultStreams: number;
  maxResults: number;
  maxResultsShorts: number;
  preferAutoGeneratedSubtitles: boolean;
  saveSubsToKVS: boolean;
  searchQueries: string[];
  sortingOrder: string;
}

//pintostudio/youtube-transcript-scraper
export interface YoutubeTranscriptConfig {
  videoUrl: string;
}
